### ISSUE TITLE
Self-installer exits with code 1

### ISSUE THREAD

**Issue by alice-rosen** [upleveled/notion-backup#279]
Hi, have everyone's daily backups been working the past few days?

I got the 401 error that I've gotten a few times, which is usually fixed by updating the token. I did that, but now I'm getting a new error:

<img width="536" alt="Screenshot 2024-07-04 at 16 44 26" src="https://github.com/upleveled/notion-backup/assets/95714438/9a3e1378-3268-4569-99c1-a18f650e5a70">

Please let me know if you need any additional information. Any advice is appreciated :)

**Comment by karlhorky** [comment]
[`pnpm/action-setup`](https://github.com/pnpm/action-setup) is a separate project, currently at v4 (in the screenshot above it is v2) - maybe check the issues in that repo?

I'll close this issue here (since it's related to the other project), and we can keep discussing, if you're still having issues.

**Comment by alice-rosen** [comment]
Thanks for this @karlhorky, that fixed it!

**Comment by karlhorky** [comment]
Nice, what was the fix?

**Comment by alice-rosen** [comment]
I just changed anywhere the `.github/workflows/export-notion-blocks-and-commit.yml` file or the `.github/workflows/lint-and-check-types.yml` file said 'v2' or 'v3' to 'v4'.

**Comment by karlhorky** [comment]
Nice! Glad it worked :)
