### ISSUE TITLE
Updating template repo based of commits

### ISSUE THREAD

**Issue by krisu5** [upleveled/notion-backup#99]
Or is updating even necessary?

**Comment by karlhorky** [comment]
Hi @krisu5 ! I'm not sure what your request means here - do you think you could expand on this?

**Comment by krisu5** [comment]
I mean the dependency upgrades [here](https://github.com/upleveled/notion-backup/commits/main) and such.

There's also for example these updates: https://github.com/upleveled/notion-backup/commit/e79e826c33764d7e893931e19861336c6d96ea19 & https://github.com/upleveled/notion-backup/commit/35ace820bc8909431077ede78fb1385c512120a3 that effect `export-notion-blocks-and-commit.yml` and `lint-and-check-types.yml`. I did the template repo **before** these updates.

Since template repo is just copy of the original repo and can't get update commits of original, I was wondering if it's OK that template just stays without updates of original. I'm kinda noob in stuff like this.

**Comment by karlhorky** [comment]
Ah, understood!

I just keep the dependencies up to date to allow fast responses to any security vulnerabilities (eg. a new security vulnerability in one of the packages used)

If you're interested in also doing this, you could [install Renovate bot](https://github.com/apps/renovate/installations/new), since the [`renovate.json`](https://github.com/upleveled/notion-backup/blob/main/renovate.json) file is already in your repository.

My renovate config (specified in the `renovate.json` file linked above) will configure Renovate bot for weekly updates (on Thursday evening CET).

If you want a different schedule (or you want updates right away), you can modify your `renovate.json` in your repo to use a different configuration. eg. the default `base` configuration, like this:

```json
{
  "extends": ["config:base"]
}
```

**Comment by krisu5** [comment]
Okay, thanks for explanation. :)
